In [4]:
import tensorflow as tf

In [5]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [9]:
tensor_one_d = tf.constant([2, 0, -3, 90, 8])
print(tensor_one_d)

tf.Tensor([ 2  0 -3 90  8], shape=(5,), dtype=int32)


In [10]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5 ,-1],
    [1, 5, 6],
    [2, 3, 8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [11]:
tensor_three_d = tf.constant([
    [
        [1, 2, 0],
        [3, 5, -1]
    ],
    [
        [10, 2, 0],
        [1, 0, 2]
    ],
    [
      [5, 8, 0],
      [2, 7, 0]  
    ],
    [
        [2, 1, 9],
        [4, -3, 32]
    ]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [15]:
print('Shape:', tensor_three_d.shape)
print('Dimensions:', tensor_three_d.ndim)

Shape: (4, 2, 3)
Dimensions: 3
