In [13]:
import tensorflow as tf
import numpy as np

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2, 0, -3, 90, 8])
print(tensor_one_d)

tf.Tensor([ 2  0 -3 90  8], shape=(5,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5 ,-1],
    [1, 5, 6],
    [2, 3, 8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [
        [1, 2, 0],
        [3, 5, -1]
    ],
    [
        [10, 2, 0],
        [1, 0, 2]
    ],
    [
      [5, 8, 0],
      [2, 7, 0]  
    ],
    [
        [2, 1, 9],
        [4, -3, 32]
    ]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print('Shape:', tensor_three_d.shape)
print('Dimensions:', tensor_three_d.ndim)

Shape: (4, 2, 3)
Dimensions: 3


In [ ]:
tensor_four_d = tf.constant([
[
    [
        [1, 2, 0],
        [3, 5, -1]
    ],
    [
        [10, 2, 0],
        [1, 0, 2]
    ],
    [
      [5, 8, 0],
      [2, 7, 0]  
    ],
    [
        [2, 1, 9],
        [4, -3, 32]
    ]
],[
    [
        [1, 9, 0],
        [11, -5, 4]
    ],
    [
        [14, 2, 0],
        [1, 0, 2]
    ],
    [
      [5, 8, 0],
      [2, 7, 0]  
    ],
    [
        [2, 22, 9],
        [4, -3, 17]
    ]
],[
[
        [1, 2, 0],
        [3, 5, -1]
    ],
    [
        [10, 2, 0],
        [1, 0, 2]
    ],
    [
      [5, 8, 0],
      [2, 7, 0]  
    ],
    [
        [2, 1, 9],
        [4, -3, 32]
    ]
]])

print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  9  0]
   [11 -5  4]]

  [[14  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2 22  9]
   [ 4 -3 17]]]


 [[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [ ]:
print('tensor_four_d details')
print('Shape:', tensor_four_d.shape)
print('Dimensions:', tensor_four_d.ndim)

tensor_four_d details
Shape: (3, 4, 2, 3)
Dimensions: 4


# Tensor data types
Casting a tensor to change it's data type   
Bool tensor   
String tensor


In [ ]:
tnsr_one_d=tf.constant([ 2,  0., -3, 90,  8], dtype=tf.float32)
casted_tnsr_one_d = tf.cast(tnsr_one_d, dtype=tf.int16)
casted_tnsr_one_d_to_bool = tf.cast(tnsr_one_d, dtype=tf.bool)
tnsr_one_d_str = tf.constant(["hellow world", "hi"])

print('tnsr_one_d:\n', tnsr_one_d)
print()
print('casted_tnsr_one_d:\n', casted_tnsr_one_d)
print()
print('casted_tnsr_one_d_to_bool:\n', casted_tnsr_one_d_to_bool)
print()
print('tnsr_one_d_str:\n', tnsr_one_d_str)

tnsr_one_d:
 tf.Tensor([ 2.  0. -3. 90.  8.], shape=(5,), dtype=float32)

casted_tnsr_one_d:
 tf.Tensor([ 2  0 -3 90  8], shape=(5,), dtype=int16)

casted_tnsr_one_d_to_bool:
 tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)

tnsr_one_d_str:
 tf.Tensor([b'hellow world' b'hi'], shape=(2,), dtype=string)


In [ ]:
np_array = np.array([1, 2, 5])
print(np_array)

[1 2 5]


In [ ]:
converted_tensor = tf.cast(np_array, dtype=tf.int32)
print(converted_tensor)

tf.Tensor([1 2 5], shape=(3,), dtype=int32)


# Methods

## eye - Identity Matrix
All elements are 0 (zero), except for the leading diagonal, populated by 1.   
Math operations can be used to modify the output of the leading diagonal.   
Changing the parameters of the method gives different tensor shapes as an output.

In [ ]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


## fill   
Creates a tensor filled with a scalar value.   
tf.fill(dims, value, name=None)

In [3]:
fill_tensor = tf.fill(
    [3, 4], 5, name=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


## ones   
Creates a tensor with all elements set to one (1)

In [6]:
ones_tensor = tf.ones(
    [5, 3, 2], 
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


## ones_like   
Creates a tensor that has the same shape as the input.

In [7]:
onelike_tensor = tf.ones_like(fill_tensor)
print(onelike_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


## zeros   
Creates a tensor with all elements set to zero (0)

In [8]:
zeros_tensor = tf.zeros(
    [5, 3, 2], 
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]], shape=(5, 3, 2), dtype=float32)


## rank   

In [17]:
t = tf.constant([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print(tf.rank(t))

tf.Tensor(2, shape=(), dtype=int32)


## size   
Returns a 0-D tensor (scalar) that represents the number of elements in input, of type out_type (default=tf.int32).

In [20]:
s = tf.size(t)
print(s)

tf.Tensor(9, shape=(), dtype=int32)


## tf.random
Ouputs values from a normal distribution.

In [27]:
random_tensor = tf.random.normal(
    [3, 2],
    mean=1.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 0.5509244   0.95485246]
 [ 1.3290042  -0.85061705]
 [ 0.9457597  -0.48064876]], shape=(3, 2), dtype=float32)


In [34]:
rand_uni_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(rand_uni_tensor)

tf.Tensor([0.65683377 0.05816972 0.08179736 0.37256396 0.34247458], shape=(5,), dtype=float32)


# Initialization and casting indexing
1:07:40