In [4]:
import tensorflow as tf

In [5]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [9]:
tensor_one_d = tf.constant([2, 0, -3, 90, 8])
print(tensor_one_d)

tf.Tensor([ 2  0 -3 90  8], shape=(5,), dtype=int32)


In [10]:
tensor_two_d = tf.constant([
    [1, 2, 0],
    [3, 5 ,-1],
    [1, 5, 6],
    [2, 3, 8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [11]:
tensor_three_d = tf.constant([
    [
        [1, 2, 0],
        [3, 5, -1]
    ],
    [
        [10, 2, 0],
        [1, 0, 2]
    ],
    [
      [5, 8, 0],
      [2, 7, 0]  
    ],
    [
        [2, 1, 9],
        [4, -3, 32]
    ]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [15]:
print('Shape:', tensor_three_d.shape)
print('Dimensions:', tensor_three_d.ndim)

Shape: (4, 2, 3)
Dimensions: 3


In [19]:
tensor_four_d = tf.constant([
[
    [
        [1, 2, 0],
        [3, 5, -1]
    ],
    [
        [10, 2, 0],
        [1, 0, 2]
    ],
    [
      [5, 8, 0],
      [2, 7, 0]  
    ],
    [
        [2, 1, 9],
        [4, -3, 32]
    ]
],[
    [
        [1, 9, 0],
        [11, -5, 4]
    ],
    [
        [14, 2, 0],
        [1, 0, 2]
    ],
    [
      [5, 8, 0],
      [2, 7, 0]  
    ],
    [
        [2, 22, 9],
        [4, -3, 17]
    ]
],[
[
        [1, 2, 0],
        [3, 5, -1]
    ],
    [
        [10, 2, 0],
        [1, 0, 2]
    ],
    [
      [5, 8, 0],
      [2, 7, 0]  
    ],
    [
        [2, 1, 9],
        [4, -3, 32]
    ]
]])

print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  9  0]
   [11 -5  4]]

  [[14  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2 22  9]
   [ 4 -3 17]]]


 [[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [23]:
print('tensor_four_d details')
print('Shape:', tensor_four_d.shape)
print('Dimensions:', tensor_four_d.ndim)

tensor_four_d details
Shape: (3, 4, 2, 3)
Dimensions: 4


# Tensor data types
Casting a tensor to change it's data type   
Bool tensor   
String tensor


In [32]:
tnsr_one_d=tf.constant([ 2,  0., -3, 90,  8], dtype=tf.float32)
casted_tnsr_one_d = tf.cast(tnsr_one_d, dtype=tf.int16)
casted_tnsr_one_d_to_bool = tf.cast(tnsr_one_d, dtype=tf.bool)
tnsr_one_d_str = tf.constant(["hellow world", "hi"])

print('tnsr_one_d:\n', tnsr_one_d)
print()
print('casted_tnsr_one_d:\n', casted_tnsr_one_d)
print()
print('casted_tnsr_one_d_to_bool:\n', casted_tnsr_one_d_to_bool)
print()
print('tnsr_one_d_str:\n', tnsr_one_d_str)

tnsr_one_d:
 tf.Tensor([ 2.  0. -3. 90.  8.], shape=(5,), dtype=float32)

casted_tnsr_one_d:
 tf.Tensor([ 2  0 -3 90  8], shape=(5,), dtype=int16)

casted_tnsr_one_d_to_bool:
 tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)

tnsr_one_d_str:
 tf.Tensor([b'hellow world' b'hi'], shape=(2,), dtype=string)


In [33]:
import numpy as np

In [34]:
np_array = np.array([1, 2, 5])
print(np_array)

[1 2 5]


In [35]:
converted_tensor = tf.cast(np_array, dtype=tf.int32)
print(converted_tensor)

tf.Tensor([1 2 5], shape=(3,), dtype=int32)


# Methods

## eye - Identity Matrix
All elements are 0 (zero), except for the leading diagonal, populated by 1.   
Math operations can be used to modify the output of the leading diagonal.   
Changing the parameters of the method gives different tensor shapes as an output.

In [40]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)
